name: CI-Foxy

on: [push, pull_request]

env:
  # ToDo:
  #CATKIN_LINT: true
  #CATKIN_LINT_ARGS: '--strict'
  ROS_DISTRO: foxy

jobs:
  testing-repo:
    name: "Build + Test with Testing Repo of foxy (http://packages.ros.org/ros2-testing/ubuntu)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing

  main-repo:
    name: "Build + Test with Main Repo of foxy (http://packages.ros.org/ros2/ubuntu)"
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: main

  clang-format:
    name: "Run clang format check"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing
          CLANG_FORMAT_CHECK: file
          CLANG_FORMAT_VERSION: 10

  clang-tidy:
    name: "Run clang-tidy check with Testing Repo of foxy (http://packages.ros.org/ros2-testing/ubuntu)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing
          CLANG_TIDY: true

# ToDo:
#  coverage:
#    name: "Coverage check for psen_scan_v2"
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v1
#      - uses: 'ros-industrial/industrial_ci@master'
#        env:
#          ROS_REPO: testing
#          ADDITIONAL_DEBS: git
#          CATKIN_LINT: false
#          NOT_TEST_BUILD: true
#          PARALLEL_TESTS: false
#          AFTER_SCRIPT: 'git clone --depth=1 --branch master https://github.com/PilzDE/industrial_ci_addons.git /industrial_ci_addons && source /industrial_ci_addons/check_coverage.sh && check_coverage psen_scan_v2'
#          CMAKE_ARGS: '-DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug'
