name: CI-Foxy

on: [push, pull_request]

env:
  ROS_DISTRO: foxy

jobs:
  testing-repo:
    name: "Build + Test with Testing Repo of foxy (http://packages.ros.org/ros2-testing/ubuntu)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing

  main-repo:
    name: "Build + Test with Main Repo of foxy (http://packages.ros.org/ros2/ubuntu)"
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: main

  # ToDo: fix headers
  # clang-tidy:
  #   name: "Run clang-tidy check with Testing Repo of foxy (http://packages.ros.org/ros2-testing/ubuntu)"
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: 'ros-industrial/industrial_ci@master'
  #       env:
  #         ROS_REPO: testing
  #         CLANG_TIDY: true
  #         NOT_TEST_BUILD: true

  coverage:
    name: "Run coverage check with Testing Repo of foxy (http://packages.ros.org/ros2-testing/ubuntu)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing
          ADDITIONAL_DEBS: git lcov
          PARALLEL_TESTS: false
          CMAKE_ARGS: '-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"'
          DOCKER_RUN_OPTS: '-e COVERAGE_EXCLUDES="*/psen_scan_v2/src/psen_scan_driver.cpp"'
          AFTER_SCRIPT: 'git clone --depth=1 --branch master https://github.com/PilzDE/industrial_ci_addons.git /industrial_ci_addons && source /industrial_ci_addons/check_coverage.sh && check_coverage psen_scan_v2'
