name: CI-rosdoc-lite check

on: [push, pull_request]

jobs:
  rosdoc_lite:
    name: "rosdoc_lite check for psen_scan_v2"
    runs-on: ubuntu-20.04
    container: ros:noetic-ros-core
    steps:
      - uses: actions/checkout@v1
      - name: Install rosdoc-lite
        run: sudo apt-get update && sudo apt-get install ros-noetic-rosdoc-lite graphviz -y
      - name: Check rosdoc_lite for errors
        shell: bash
        run: /bin/bash .rosdoc_lite_check.sh
